pipeline:
  - !LinearController
    low_utilisation: 0.50
    high_allocation: 0.90
    rate: 16
    interval: 1
  - !Limiter
    minimum: 1
    maximum: CONFIGURE_COBALD_TARDIS_CLUSTER_CAPACITY
  - !Logger
    name: 'changes'
  - !TardisPoolFactory
    configuration: 'tardis.yml'

logging:
    version: 1
    root:
        level: DEBUG
        handlers: [console]
    formatters:
        precise:
            format: '%(name)s: %(asctime)s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: precise
            stream  : ext://sys.stdout
